### ISSUE TITLE
Title Bar is not showing

### ISSUE THREAD

**Issue by e-labInnovations** [Treverix/custom-electron-titlebar#4]
**Describe the bug**
Not working your example

**To Reproduce**
Just copied your example codes and run `npm start`

**Expected behaviour**
After installing `custom-electron-titlebar` package I got an error. So I installed `@treverix/remote`
But it's not working anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/33958126/91998360-be125980-ed58-11ea-98c2-d42a18b730ae.png)

**Desktop:**
 - OS: Windows 7 
 - Electron version 10.1.1
 - Node Version 10.16.3

**Comment by Mohatje** [comment]
Make sure you've deleted line 12 and uncommented line 11.

Delete: 
https://github.com/Treverix/custom-electron-titlebar/blob/6dc6af79c5e06b05babba10233809a88b4917f2c/example/preload.js#L12

Uncomment: 
https://github.com/Treverix/custom-electron-titlebar/blob/6dc6af79c5e06b05babba10233809a88b4917f2c/example/preload.js#L11

**Comment by Treverix** [comment]
What @Mohatje found could be the reason. I probably update the example so that it is usable by default (and I uncomment when I want to use it for development ;) )

I also updated `@treverix/remote`. So `ncu -u` is worth a try. 

The example code got updated on the latest release: https://github.com/Treverix/custom-electron-titlebar/releases/tag/4.1.3

**Comment by Treverix** [comment]
Closed after inactivity
